### PR TITLE
feat: new website

### LINKED ISSUE #17: Equal sized cards on events and team page
To make the page design look more consistent, it would be better to have equal sized cards on the events and team pages. Event and team member image sizes may need to be adjusted to do the same.

### PR DESCRIPTION
**Pull request by RoneelV**
resolves #17

### CODE REVIEW

**Review by meet59patel — APPROVED** [review]
LGTM!
GG @RoneelV @prakhartech @miti2001 🚀🚀

**Comment by RoneelV** [comment]
@all-contributors please add @RoneelV for code and design

**Comment by RoneelV** [comment]
@all-contributors please add @prakhartech for code and design

**Comment by RoneelV** [comment]
@all-contributors please add @miti2001 for code and design

**Pull request merged**
